# version: "3.7"

# services:
#   mysql-db:
#     container_name: mysql-db
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD:
#       MYSQL_DATABASE: online_shop_db
#     ports:
#       - '3308:3306'
#     volumes:
#         - ./database:/var/lib/mysql
#     networks:
#         - backend
  
#   backend_flask:
#     build:
#       context: ./
#     ports:
#       - 5000:5000
  
# networks:
#     backend:

# volumes:
#     app:
#     database:

